*** Settings ***
Documentation    Mapeamento de locators da aba 'Send Quote'.

*** Variables ***

${SEND_QUOTE_EMAIL_INPUT}                   id=email
${SEND_QUOTE_PHONE_INPUT}                   id=phone
${SEND_QUOTE_USERNAME_INPUT}                id=username
${SEND_QUOTE_PASSWORD_INPUT}                id=password
${SEND_QUOTE_CONFIRM_PASSWORD_INPUT}        id=confirmpassword
${SEND_QUOTE_COMMENTS_TEXTAREA}             id=Comments
${SEND_QUOTE_PREV_BUTTON}                   id=prevselectpriceoption
${SEND_QUOTE_SEND_BUTTON}                   id=sendemail
